rgb_topic: /kinect2/hd/image_color_rect
depth_topic: /kinect2/sd/image_depth_rect
publish_rate: 10.0
min_area: 500
change_threshold_m: 0.1
depth_min_m: 0.1
depth_max_m: 10.0
h1_min: 0
h1_max: 10
s1_min: 120
s1_max: 255
v1_min: 70
v1_max: 255
h2_min: 170
h2_max: 180
s2_min: 120
s2_max: 255
v2_min: 70
v2_max: 255
