cmd_topic: "/cmd_vel"
image_width: 1920.0

control_rate: 20.0
lost_timeout: 0.6

kp_angular: 1.4
kp_linear: 2.6

max_linear_x: 0.35
max_angular_z: 1.5

deadband_x: 0.05
deadband_size: 0.006
target_area_ratio: 0.020

smooth_alpha: 0.35
search_angular_z: 0.35
